import React, { Suspense } from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import './i18n';
import './styles/tokens.css';
import './styles/base.css';
import './styles/utilities.css';
import App from './App';
// Synced from the repo-root amplify_outputs.json by scripts/sync-amplify-outputs.mjs
// (runs on prestart/prebuild). Kept inside src/ because CRA forbids importing
// from outside the src/ directory.
import outputs from './amplify_outputs.json';

// Configure Amplify from the outputs generated by `npx ampx sandbox` / the
// Amplify Hosting pipeline. Guarded so the app still boots before the backend
// is provisioned (placeholder outputs); feed pages then show an empty state.
try {
  Amplify.configure(outputs);
} catch (e) {
  // eslint-disable-next-line no-console
  console.warn('[amplify] Not configured yet — run `npx ampx sandbox`.', e);
}

const Splash = () => (
  <div
    style={{
      minHeight: '100svh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: '#101F2C',
    }}
    aria-label="Loading"
  />
);

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <Suspense fallback={<Splash />}>
      <App />
    </Suspense>
  </React.StrictMode>
);
